USE RETAILSALESDB;

-- Total number of orders
SELECT COUNT(*) AS total_orders FROM orders;

-- Total number of customers
SELECT COUNT(*) AS total_customers FROM customers;

-- Total number of products
SELECT COUNT(*) AS total_products FROM products;


-- Most frequently ordered products (Top 10)
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_quantity
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity DESC
LIMIT 10;


-- Average Order Value (AOV)
SELECT 
    AVG(order_total) AS avg_order_value
FROM (
    SELECT 
        oi.order_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS order_total
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
) t;


-- Monthly revenue trend
SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(t.revenue) AS revenue
FROM orders o
JOIN (
    SELECT 
        oi.order_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
) t ON o.order_id = t.order_id
GROUP BY month
ORDER BY month;


-- Top 5 states generating highest revenue
SELECT 
    c.state,
    SUM(t.revenue) AS revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN (
    SELECT 
        oi.order_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
) t ON o.order_id = t.order_id
GROUP BY c.state
ORDER BY revenue DESC
LIMIT 5;

-- Monthly active customers
SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(DISTINCT customer_id) AS customers
FROM orders
GROUP BY month
ORDER BY month;


-- New vs Returning customers
SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    COUNT(DISTINCT CASE 
        WHEN c.registration_date = o.order_date THEN c.customer_id 
    END) AS new_customers,
    COUNT(DISTINCT CASE 
        WHEN c.registration_date < o.order_date THEN c.customer_id 
    END) AS returning_customers
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY month
ORDER BY month;


-- Top 10 customers by total spending
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS name,
    SUM(t.revenue) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN (
    SELECT 
        oi.order_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
) t ON o.order_id = t.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC
LIMIT 10;


-- Gender-wise spending distribution
SELECT 
    c.gender,
    SUM(t.revenue) AS total_spending
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN (
    SELECT 
        oi.order_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
) t ON o.order_id = t.order_id
GROUP BY c.gender;


-- Churn prediction (no orders in last 6 months)
SELECT 
    customer_id,
    MAX(order_date) AS last_order
FROM orders
GROUP BY customer_id
HAVING last_order < DATE_SUB(CURDATE(), INTERVAL 6 MONTH);

-- Best selling products by quantity
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC;


-- Revenue by product category
SELECT 
    p.category,
    SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category;


-- Profit generated by each product
SELECT 
    p.product_name,
    SUM((p.unit_price - p.cost_price) * oi.quantity) AS profit
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY profit DESC;


-- Underperforming products (low sales)
SELECT 
    p.product_name,
    COALESCE(SUM(oi.quantity), 0) AS total_sales
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING total_sales < 10;

-- 🔹 4. SHIPPING & FULFILMENT

-- Average shipping time
SELECT 
    AVG(DATEDIFF(s.shipping_date, o.order_date)) AS avg_shipping_days
FROM shipping s
JOIN orders o ON s.order_id = o.order_id;


-- Shipping cost analysis
SELECT 
    AVG(shipping_cost) AS avg_cost,
    MAX(shipping_cost) AS max_cost,
    MIN(shipping_cost) AS min_cost
FROM shipping;


-- Delayed vs On-time delivery
SELECT 
    CASE 
        WHEN DATEDIFF(s.shipping_date, o.order_date) > 5 THEN 'Delayed'
        ELSE 'On-Time'
    END AS delivery_status,
    COUNT(*) AS total_orders
FROM shipping s
JOIN orders o ON s.order_id = o.order_id
GROUP BY delivery_status;


-- Order distribution by shipping status
SELECT 
    shipping_status,
    COUNT(*) AS total_orders
FROM shipping
GROUP BY shipping_status;

-- Ranking customers based on spending (optimized)
SELECT 
    t.customer_id,
    t.total_spent,
    @rank := @rank + 1 AS customer_rank
FROM (
    SELECT 
        c.customer_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS total_spent
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY c.customer_id
    ORDER BY total_spent DESC
    LIMIT 100
) t,
(SELECT @rank := 0) r;


-- Customer segmentation using CASE
SELECT 
    customer_id,
    CASE 
        WHEN total_spent > 5000 THEN 'High Value'
        WHEN total_spent > 2000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS segment
FROM (
    SELECT 
        c.customer_id,
        SUM((p.unit_price * oi.quantity) - COALESCE(oi.discount,0)) AS total_spent
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY c.customer_id
) t;

