CREATE DATABASE DTFORMER;

USE DTFORMER;

CREATE TABLE CUSTOMER(                     
CUSTOMERID INT PRIMARY KEY,
FIRSTNAME VARCHAR (50),
LASTNAME VARCHAR (50),
EMAIL VARCHAR (80),
REGISTRATIONDATE DATE
);
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, REGISTRATIONDATE) 
VALUES
(1, 'HARDIK', 'PATEL', 'HARDIKPATEL23@GMAIL.COM', '2025-11-16'),
(2, 'RAHUL', 'SHAH', 'RAHUL.SHAH22@GMAIL.COM', '2025-01-05'),
(3, 'NILESH', 'DESAI', 'NILESH.DESAI33@GMAIL.COM', '2025-01-12'),
(4, 'SURESH', 'JOSHI', 'SURESH.JOSHI44@GMAIL.COM', '2025-01-18'),
(5, 'PANKAJ', 'VYAS', 'PANKAJ.VYAS55@GMAIL.COM', '2025-01-24'),
(6, 'MAHESH', 'PARMAR', 'MAHESH.PARMAR66@GMAIL.COM', '2025-02-02'),
(7, 'JAYANT', 'BHATT', 'JAYANT.BHATT77@GMAIL.COM', '2025-02-10');

CREATE TABLE ORDERS(
ORDERID INT PRIMARY KEY,
CUSTOMERID INT,
ORDERDATE DATE,
TOTALAMOUNT DECIMAL,
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER (CUSTOMERID)
);

INSERT INTO ORDERS (ORDERID, CUSTOMERID, ORDERDATE, TOTALAMOUNT)
VALUES
(101, 1, '23-07-01', 15550.50),
(102, 2, '23-06-11', 2000.10),
(103, 3, '23-07-15', 3500.89),
(104, 4, '23-07-08', 16000.45),
(105, 5, '23-07-09', 1344.23),
(106, 6, '23-05-22', 5555.33),
(107, 7, '23-08-19', 6766.5);

CREATE TABLE EMPLOYEE(
EMPLOYEEID INT PRIMARY KEY,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
DEPARTMENT VARCHAR(80),
HIREDATE DATE,
SALARY INT
);

INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME, DEPARTMENT, HIREDATE, SALARY)
VALUES
(1, 'RAHUL', 'SHARMA', 'IT', '2023-01-15', 50000),
(2, 'PRIYA', 'PATEL', 'HR', '2022-08-10', 42000),
(3, 'AMIT', 'VERMA', 'FINANCE', '2021-05-20', 60000),
(4, 'NEHA', 'SINGH', 'MARKETING', '2024-02-01', 38000),
(5, 'KARAN', 'MEHTA', 'IT', '2020-11-12', 70000),
(6, 'POOJA', 'DESAI', 'SALES', '2023-06-18', 45000);

-- 1..RETRIEVE ALL ORDERS AND CUSTOMER DETAILS WHERE ORDERS EXIST.
SELECT * FROM CUSTOMER AS C
INNER JOIN ORDERS AS O
ON c.CustomerID = o.CustomerID;

-- 2..RETRIEVE ALL CUSTOMERS AND THEIR CORRESPONDING ORDERS (IF ANY).
SELECT * FROM CUSTOMER AS C
LEFT JOIN ORDERS AS O
ON C.CUSTOMERID = O.CUSTOMERID;

-- 3..RETRIEVE ALL ORDERS AND THEIR CORRESPONDING CUSTOMERS (IF ANY).
SELECT * FROM ORDERS AS O
LEFT JOIN CUSTOMER AS C
ON O.CUSTOMERID = C.CUSTOMERID;

-- 4..RETRIEVE ALL CUSTOMERS AND ALL ORDERS, REGARDLESS OF MATCHING.
SELECT * FROM CUSTOMER AS C
LEFT JOIN ORDERS AS O
ON C.CUSTOMERID = O.CUSTOMERID;

-- 5..SUBQUERY TO FIND CUSTOMERS WHO HAVE PLACED ORDERS WORTH MORE THAN THE AVERAGE AMOUNT.
SELECT FIRSTNAME, LASTNAME FROM CUSTOMER WHERE CUSTOMERID IN (
SELECT CUSTOMERID FROM ORDERS WHERE TOTALAMOUNT >
(SELECT AVG(TOTALAMOUNT) FROM ORDERS)
);

-- 6..SUBQUERY TO FIND EMPLOYEES WITH SALARIES ABOVE THE AVERAGE SALARY.
SELECT FIRSTNAME, LASTNAME, SALARY FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

-- 7..EXTRACT THE YEAR AND MONTH FROM THE ORDERDATE.
SELECT ORDERID, YEAR(ORDERDATE) AS ORDER_YEAR,
MONTH(ORDERDATE) AS ORDER_MONTH FROM ORDERS;

-- 8..CALCULATE THE DIFFERENCE IN DAYS BETWEEN TWO DATES (ORDER DATE AND CURRENT DATE).
SELECT ORDERID,
DATEDIFF(CURDATE(), ORDERDATE) AS DAYS_DIFFERENCE FROM ORDERS;

-- 9..FORMAT THE ORDERDATE TO A MORE READABLE FORMAT (E.G., DD-MM-YYYY).
SELECT ORDERID,
DATE_FORMAT(ORDERDATE, '%d-%m-%Y') AS FORMATTED_DATE FROM ORDERS;

-- 10..CONCATENATE FIRSTNAME AND LASTNAME TO FORM A FULL NAME.
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULL_NAME FROM CUSTOMER;

-- 11..REPLACE PART OF A STRING (E.G., REPLACE ‘hardik’ WITH ‘harsh’).
SELECT REPLACE(FIRSTNAME, 'HARDIK', 'HARSH') AS UPDATED_NAME
FROM CUSTOMER;

-- 12..CONVERT FIRSTNAME TO UPPERCASE AND LASTNAME TO LOWERCASE.
SELECT UPPER(FIRSTNAME) AS FIRSTNAME_UPPER,
LOWER(LASTNAME) AS LASTNAME_LOWER FROM CUSTOMER;

-- 13..TRIM EXTRA SPACES FROM THE EMAIL FIELD.
SELECT TRIM(EMAIL) AS CLEAN_EMAIL FROM CUSTOMER;

-- 14..CALCULATE THE RUNNING TOTAL OF TOTALAMOUNT FOR EACH ORDER.
SELECT ORDERID, ORDERDATE, TOTALAMOUNT,
SUM(TOTALAMOUNT) OVER (ORDER BY ORDERDATE) AS RUNNING_TOTAL FROM ORDERS;

-- 15..RANK ORDERS BASED ON TOTALAMOUNT USING THE RANK() FUNCTION.
SELECT ORDERID, ORDERDATE, TOTALAMOUNT,
SUM(TOTALAMOUNT) OVER (ORDER BY ORDERDATE) AS RUNNING_TOTAL FROM ORDERS;

-- 16..ASSIGN A DISCOUNT BASED ON TOTALAMOUNT IN ORDERS (E.G., > 1000: 10% OFF, > 500: 5% OFF).
SELECT ORDERID, TOTALAMOUNT, IF(TOTALAMOUNT > 1000, '10% DISCOUNT',
IF(TOTALAMOUNT > 500, '5% DISCOUNT', 'NO DISCOUNT')
) AS DISCOUNT
FROM ORDERS;

-- 17..CATEGORIZE EMPLOYEES’ SALARIES AS HIGH, MEDIUM, OR LOW.
SELECT FIRSTNAME, SALARY, IF(SALARY >= 60000, 'HIGH',
IF(SALARY >= 40000, 'MEDIUM', 'LOW')
) AS SALARY_LEVEL
FROM EMPLOYEE;






 