print("welcome to the practical test program!"  )
print()
name= input("enter your name: " )
age = int (input("enter your age:"))
height = input("enter your height in metres: ")
number = input("enter your favourite number: ")

print()
print("here we go! here are your all information collected ")
print()
print("Name: ", name , "(type: ", type(name), "memory address:", id(name), ")")
print("Age:", age , "(type: ", type (age), "memory address:", id(age), ")")
print("Height: ", height , "(type: ", type(height), "memory address:", id(height), ")")
print("Favourite Number: ", number , "(type: ", type(number), "memory address:", id(number), ")")
print()
print("you were born in the year of", 2025 - int(age))
print()
print("Thank you for giving your data program, Aryan Sir! ")